debug: true
mlflow_uri: file:./experiments/results
exp_name: cartpole

num_envs: 1
num_episodes: 1000
max_steps: 500
eps_max: 0.5
eps_min: 0.01
render: true

defaults:
  - _self_
  - agents: dqn

hydra:
  output_subdir: null
  run:
    dir: .
