debug: true
mlflow_uri: file:./experiments/results
exp_name: cartpole

n_envs: 4
n_episodes: 1000
max_steps: 500
eps_max: 1.0
eps_min: 0.01
eps_decay: 0.99
render: true

defaults:
  - _self_
  - agents: dqn

hydra:
  output_subdir: null
  run:
    dir: .
