env_name: CartPole-v1
lr: 1e-4
gamma: 0.99
batch_size: 64
n_episodes: 1000
max_steps: 200
eps_max: 1.0
eps_min: 0.01
eps_decay: 0.99
hidden_size: 64
render: true

defaults:
  - _self_
  - agents: dqn

hydra:
  output_subdir: null
  run:
    dir: .
